### ISSUE TITLE
Cannot Import team_id in multi tenant with import excel

### ISSUE THREAD

**Issue by erdowaka** [zymhmss/Filament-Starter-Kit#5]
hai.... i'm waka, can you solve my problem ?
my promblem just how to insert team_id using file import excel in multi tenant.. can you solve for this with example page ? just simple page ?

**Comment by zymhmss** [comment]
Dear brother,

Ling Myat will reply from GitHub issue.

Best Regard,

________________________________
From: Erdo Waka Septyano ***@***.***>
Sent: Thursday, February 15, 2024 2:43 PM
To: zymhmss/Filament-Starter-Kit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zymhmss/Filament-Starter-Kit] Cannot Import team_id in multi tenant with import excel (Issue #5)


hai.... i'm waka, can you solve my problem ?
my promblem just how to insert team_id using file import excel in multi tenant.. can you solve for this with example page ? just simple page ?

**Comment by LingMyat** [comment]
Hello waka,

You can use laravel observer or you can set default columns value in your import file

```php
public function resolveRecord(): ? YourModel
{
        return new YourModel([
            'registered_code' => strtoupper(
                substr(
                    str_replace(
                        '-', '',Str::uuid()->toString()
                    ),-12
                )
            ),
            'created_by' => auth()->id(),
            'team_id'    => Filament::getTenant()->id,
            'exam_id'    => explode('/', parse_url(URL::previous())['path'])[4],
        ]);
}
```

**Comment by erdowaka** [comment]
thank's for your reply and this what i want, thanks alot
